# Generated by Django 5.0.4 on 2024-04-28 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_proveedor_producto_stock_actual_producto_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compra.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.IntegerField(default=0, verbose_name='Stock actual'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='dni',
            field=models.IntegerField(verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
